In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Задание 1

In [2]:
data0= pd.read_csv('D:\ML\data\diabetes.csv')
data0=data0.astype(int)
data0.drop_duplicates()
data0['Diabetes_012'].loc[data0['Diabetes_012']==2]=1
data0.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0             0       1         1          1   40       1       0   
1             0       0         0          0   25       1       0   
2             0       1         1          1   28       0       0   
3             0       1         0          1   27       0       0   
4             0       1         1          1   24       0       0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                     0             0       0  ...              1   
1                     0             1       0  ...              0   
2                     0             0       1  ...              1   
3                     0             1       1  ...              1   
4                     0             1       1  ...              1   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  \
0            0        5        18        15         1    0    9          4   
1            1        3         0         0         0    0    7          6   
2            1        5        30        30         1    0    9          4   
3            0        2         0         0         0    0   11          3   
4            0        2         3         0         0    0   11          5   

   Income  
0       3  
1       1  
2       8  
3       6  
4       4  

[5 rows x 22 columns]

In [3]:
data= pd.read_csv('D:\ML\data\kc_house_data.csv')
data['bathrooms']=data['bathrooms'].astype(int)
data['price']=data['price'].astype(int)
data.pop('date')
data.pop('id')
data.pop('lat')
data.pop('long')
data.pop('zipcode')
data['cherdak']=(data['floors']%1*2).astype(int)
data['floors']=data['floors'].astype(int)
data=data.drop_duplicates()
data.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900         3          1         1180      5650       1           0   
1  538000         3          2         2570      7242       2           0   
2  180000         2          1          770     10000       1           0   
3  604000         4          3         1960      5000       1           0   
4  510000         3          2         1680      8080       1           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   sqft_living15  sqft_lot15  cherdak  
0           1340        5650        0  
1           1690        7639        0  
2           2720        8062        0  
3           1360        5000        0  
4           1800        7503        0

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X=data.drop(['price'],axis=1)
Y=data['price']
X0=data0.drop(['Diabetes_012'],axis=1)
Y0=data0['Diabetes_012']

x_train,x_test,y_train,y_test= train_test_split(X,Y, test_size=0.2)
x0_train,x0_test,y0_train,y0_test= train_test_split(X0,Y0, test_size=0.2)

In [6]:
import tensorflow as tf
import keras

In [7]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import confusion_matrix, classification_report

In [8]:
# создаем модель, как набор последовательных слоев
model_regression = tf.keras.Sequential(
    [
        # Dense - полносвязный слой (каждый нейрон следующего слоя связан со всеми нейронами предыдущего)
        tf.keras.layers.Dense(64, activation="relu", input_shape=(16,)),
        # на втором скрытом слое будет 32 нейрона
        tf.keras.layers.Dense(32, activation="linear"),
        # Dropout позволяет внести фактор случайности - при обучении часть нейронов будет отключаться
        # каждый нейрон, в данном случае, будет отключаться с вероятностью 0.1
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dropout(0.1),
        # на выходе один нейрон, функция активации не применяется
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [9]:
model_regression.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1088      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 3713 (14.50 KB)
Trainable params: 3713 (14

In [10]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [12]:
model_regression.fit(x_train, y_train, epochs=20)

Epoch 1/20
541/541 [==============================] - 1s 1ms/step - loss: 68667006976.0000
Epoch 2/20
541/541 [==============================] - 1s 1ms/step - loss: 68106596352.0000
Epoch 3/20
541/541 [==============================] - 1s 1ms/step - loss: 65990774784.0000
Epoch 4/20
541/541 [==============================] - 1s 1ms/step - loss: 63176744960.0000
Epoch 5/20
541/541 [==============================] - 1s 1ms/step - loss: 63175139328.0000
Epoch 6/20
541/541 [==============================] - 1s 1ms/step - loss: 63501189120.0000
Epoch 7/20
541/541 [==============================] - 1s 1ms/step - loss: 61438431232.0000
Epoch 8/20
541/541 [==============================] - 1s 1ms/step - loss: 61402390528.0000
Epoch 9/20
541/541 [==============================] - 1s 1ms/step - loss: 61959901184.0000
Epoch 10/20
541/541 [==============================] - 1s 1ms/step - loss: 57037856768.0000
Epoch 11/20
541/541 [==============================] - 1s 1ms/step - loss: 60197687296.00

In [13]:
print(mean_absolute_error(y_test, model_regression.predict(x_test)))
print(mean_squared_error(y_test, model_regression.predict(x_test)))

136/136 [==============================] - 0s 920us/step
147267.6735886164
136/136 [==============================] - 0s 918us/step
47683618088.06222


In [14]:
model_regression.save("neuroRegressor.keras")

А теперь классификация

In [19]:
model_classification = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(21,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

In [20]:
w0 = 1 / y0_train[y0_train==0].shape[0]
w1 = 1 / y0_train[y0_train==1].shape[0]

In [21]:
model_classification.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="binary_crossentropy")
model_classification.fit(x0_train, y0_train, epochs=5, verbose=None,
                           class_weight={0: w0, 1: w1})

In [22]:
model_classification.predict(x0_test, verbose=None)[:5]

array([[0.29119053],
       [0.0201563 ],
       [0.02369957],
       [0.3374721 ],
       [0.2641847 ]], dtype=float32)

In [23]:
y0_pred = np.around(model_classification.predict(x0_test, verbose=None))

In [24]:
print(classification_report(y0_test, y0_pred))
print(confusion_matrix(y0_test, y0_pred))

              precision    recall  f1-score   support

           0       0.94      0.73      0.82     42807
           1       0.34      0.74      0.46      7929

    accuracy                           0.73     50736
   macro avg       0.64      0.74      0.64     50736
weighted avg       0.84      0.73      0.77     50736

[[31416 11391]
 [ 2088  5841]]


# Задание 2

In [151]:
class MLP:
    def __init__(self, num_layers, num_neurons, activation_functions):
        self.num_layers = num_layers
        self.num_neurons = num_neurons
        self.activation_functions = activation_functions

        self.weights = []
        self.biases = []

        for i in range(self.num_layers):
            if i == 0:
                input_size = self.num_neurons[i]
            else:
                input_size = self.num_neurons[i-1]

            weight = np.random.randn(input_size, self.num_neurons[i])
            bias = np.zeros((1, self.num_neurons[i]))

            self.weights.append(weight)
            self.biases.append(bias)

#    def lin(self, x):
#        return x

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def relu(self, x):
        return np.maximum(0, x)

    def tanh(self, x):
        return np.tanh(x)

    def forward(self, X):
        self.layer_outputs = []
        self.activations = []

        input_data = X
        for i in range(self.num_layers):
            layer_output = np.dot(input_data, self.weights[i]) + self.biases[i]

           # print(layer_output)
            
            if self.activation_functions[i] == 'sigmoid':
                activation = self.sigmoid(layer_output)
            elif self.activation_functions[i] == 'relu':
                activation = self.relu(layer_output)
            elif self.activation_functions[i] == 'tanh':
                activation = self.tanh(layer_output)
            elif self.activation_functions[i] == 'lin':
                activation = self.lin(layer_output)
            else:
                raise ValueError('Unknown activation function')

            self.layer_outputs.append(layer_output)
            self.activations.append(activation)

            input_data = activation

        return activation

    def backward(self, X, y, learning_rate):
        batch_size = X.shape[0]

        gradients = []
        for i in reversed(range(self.num_layers)):
            if i == self.num_layers - 1:
                output_error = self.activations[i] - y
            else:
                output_error = np.dot(gradients[0], self.weights[i+1].T)

            activation_derivative = self.derivative(self.activation_functions[i], self.layer_outputs[i])

            gradient = output_error * activation_derivative

           # print("gradient:",gradient)
            
            gradients.insert(0, gradient)

            batch_size = X.shape[0] if i == 0 else self.activations[i-1].shape[0]
            weight_gradient = np.dot(self.activations[i], gradient.T) / batch_size
            bias_gradient = np.mean(gradient, axis=0, keepdims=True)

           # print( "weight_gradient:",weight_gradient )
            
            self.weights[i] =self.weights[i]-( learning_rate * weight_gradient )
            self.biases[i] =self.biases[i]-( learning_rate * bias_gradient)

    def derivative(self, activation_function, x):
        if activation_function == 'sigmoid':
            return self.sigmoid(x) * (1 - self.sigmoid(x))
        elif activation_function == 'relu':
            return np.where(x <= 0, 0, 1)
        elif activation_function == 'tanh':
            return 1 - np.tanh(x) ** 2
   #     elif activation_function == 'lin':
    #        return 1
        else:
            raise ValueError('Unknown activation function')

    def fit(self, X_train, y_train, epochs, learning_rate):
        for epoch in range(epochs):
            indices = np.random.permutation(X_train.shape[0])
            X_train_shuffled = X_train[indices]
            y_train_shuffled = y_train[indices]

            for i in range(0, X_train.shape[0]):
                X_batch = X_train_shuffled[i:i+1]
                y_batch = y_train_shuffled[i:i+1]

           #     if i==2:
           #         print(X_batch)
                
                self.forward(X_batch)

            #    print("")
                
                self.backward(X_batch, y_batch, learning_rate)

    def predict(self, X):
        #prediction=[]
       # for i in range(X.shape[0]):
       #      prediction.append(self.forward(i))
        return self.forward(X)
    def print_activations(self):
        for i in  self.activations:
            print(i)
    def print_levels(self):
        for i in   self.layer_outputs:
            print(i)

In [152]:
mlp = MLP(num_layers=3, num_neurons=[16, 13,1], activation_functions=['relu', 'relu', 'tanh'])
mlp.fit(np.array(x_train), np.array(y_train), epochs=1, learning_rate=0.05)


In [153]:
mlp.print_activations()

[[  632.36036809     0.           845.49583632     0.
  10493.31321458     0.             0.             0.
   3424.72519475  3374.37379463     0.             0.
      0.          2016.90212702     0.             0.        ]]
[[   0.            0.            0.            0.         4149.14049271
     0.            0.            0.            0.            0.
     0.            0.         4932.93789313]]
[[-1.]]


In [154]:
mlp.print_levels()

[[  632.36036809 -1209.36589057   845.49583632 -2141.94371785
  10493.31321458 -1699.83958532 -6859.29560634 -2463.64711625
   3424.72519475  3374.37379463 -4363.15277324  -660.02743602
  -5585.15589055  2016.90212702 -4413.5138469  -3681.09306739]]
[[  -278.64215835 -11702.49167732  -7397.68171475  -5138.35457118
    4149.14049271  -9327.57067255  -8454.62823757  -5703.64357048
   -5192.75851141 -12372.07612988 -11962.44315783 -17845.25412046
    4932.93789313]]
[[-2651.57373411]]


In [155]:
y_pred_mlp = mlp.predict(np.array(x_test))

In [156]:
print(mean_absolute_error(y_test, np.array(y_pred_mlp)))
print(mean_squared_error(y_test,  np.array(y_pred_mlp)))

542732.358859697
431557874101.0037


In [157]:
mlp0 = MLP(num_layers=3, num_neurons=[21, 32, 1], activation_functions=['relu', 'sigmoid', 'sigmoid'])
mlp0.fit(np.array(x0_train), np.array(y0_train), epochs=1, learning_rate=0.005)
y0_pred_mlp = mlp0.predict(x0_test)

C:\Users\ov00v\AppData\Local\Temp\ipykernel_5724\2784707162.py:26: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [158]:
y0_pred_mlp

array([[0.040869  ],
       [0.03373071],
       [0.00023306],
       ...,
       [0.00017029],
       [0.05121255],
       [0.00116756]])

In [159]:
y0_pred_mlp = np.around(y0_pred_mlp)

In [160]:
print(classification_report(y0_test, y0_pred_mlp))
print(confusion_matrix(y0_test, y0_pred_mlp))

              precision    recall  f1-score   support

           0       0.84      1.00      0.92     42807
           1       0.00      0.00      0.00      7929

    accuracy                           0.84     50736
   macro avg       0.42      0.50      0.46     50736
weighted avg       0.71      0.84      0.77     50736

[[42802     5]
 [ 7929     0]]
